// export const Sidebarcomponents = [
//     { path: `${import.meta.env.BASE_URL}dashboards/crm`, title: 'Crm' },
//     { path: `${import.meta.env.BASE_URL}dashboards/ecommerce`, title: 'Ecommerce' },
//     { path: `${import.meta.env.BASE_URL}dashboards/crypto`, title: 'Crypto' },
//     { path: `${import.meta.env.BASE_URL}dashboards/jobs`, title: 'Jobs' },
//     { path: `${import.meta.env.BASE_URL}dashboards/nft`, title: 'Nft' },
//     { path: `${import.meta.env.BASE_URL}dashboards/sales`, title: 'Sales' },
//     { path: `${import.meta.env.BASE_URL}dashboards/analytics`, title: 'Analytics' },
//     { path: `${import.meta.env.BASE_URL}dashboards/projects`, title: 'Projects' },
//     { path: `${import.meta.env.BASE_URL}dashboards/hrm`, title: 'Hrm' },
//     { path: `${import.meta.env.BASE_URL}dashboards/stocks`, title: 'Stocks' },
//     { path: `${import.meta.env.BASE_URL}dashboards/courses`, title: 'Courses' },
//     { path: `${import.meta.env.BASE_URL}dashboards/personal`, title: 'Personal' },

//     { path: `${import.meta.env.BASE_URL}pages/aboutus`, title: 'Aboutus' },

//     { path: `${import.meta.env.BASE_URL}pages/blog/blog`, title: 'Blog' },
//     { path: `${import.meta.env.BASE_URL}pages/blog/blogdetails`, title: 'Blogdetails' },
//     { path: `${import.meta.env.BASE_URL}pages/blog/createblog`, title: 'Createblog' },

//     { path: `${import.meta.env.BASE_URL}pages/chat`, title: 'Chat' },
//     { path: `${import.meta.env.BASE_URL}pages/contacts`, title: 'Contacts' },
//     { path: `${import.meta.env.BASE_URL}pages/contactus`, title: 'Contactus' },

//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/addproducts`, title: 'Addproducts' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/cart`, title: 'Cart' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/checkout`, title: 'Checkout' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/editproducts`, title: 'Editproducts' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/orderdetails`, title: 'Orderdetails' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/orders`, title: 'Orders' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/products`, title: 'Products' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/productdetails`, title: 'Productdetails' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/productlist`, title: 'Productlist' },
//     { path: `${import.meta.env.BASE_URL}pages/ecommerce/wishlist`, title: 'Wishlist' },

//     { path: `${import.meta.env.BASE_URL}pages/email/mailapp`, title: 'Mailapp' },
//     { path: `${import.meta.env.BASE_URL}pages/email/mailsettings`, title: 'Mailsettings' },

//     { path: `${import.meta.env.BASE_URL}pages/empty`, title: 'Empty' },
//     { path: `${import.meta.env.BASE_URL}pages/faqs`, title: 'Faqs' },

//     { path: `${import.meta.env.BASE_URL}pages/filemanager/filemanager`, title: 'Filemanager' },

//     { path: `${import.meta.env.BASE_URL}pages/invoice/createinvoice`, title: 'Createinvoice' },
//     { path: `${import.meta.env.BASE_URL}pages/invoice/invoicedetails`, title: 'Invoicedetails' },
//     { path: `${import.meta.env.BASE_URL}pages/invoice/invoicelist`, title: 'Invoicelist' },

//     { path: `${import.meta.env.BASE_URL}pages/landing`, title: 'Landing' },
//     { path: `${import.meta.env.BASE_URL}pages/jobslanding`, title: 'Jobslanding' },
//     { path: `${import.meta.env.BASE_URL}pages/notifications`, title: 'Notifications' },
//     { path: `${import.meta.env.BASE_URL}pages/pricing`, title: 'Pricing' },
//     { path: `${import.meta.env.BASE_URL}pages/profile`, title: 'Profile' },
//     { path: `${import.meta.env.BASE_URL}pages/reviews`, title: 'Reviews' },
//     { path: `${import.meta.env.BASE_URL}pages/team`, title: 'Team' },
//     { path: `${import.meta.env.BASE_URL}pages/termsconditions`, title: 'Termsconditions' },
//     { path: `${import.meta.env.BASE_URL}pages/timeline`, title: 'Timeline' },
//     { path: `${import.meta.env.BASE_URL}pages/todolist`, title: 'Todolist' },

//     { path: `${import.meta.env.BASE_URL}task/kanbanboard/`, title: 'Kanbanboard' },
//     { path: `${import.meta.env.BASE_URL}task/listview/`, title: 'Listview' },
//     { path: `${import.meta.env.BASE_URL}task/taskdetails/`, title: 'Taskdetails' },

//     { path: `${import.meta.env.BASE_URL}authentication/comingsoon`, title: 'Comingsoon' },
//     { path: `${import.meta.env.BASE_URL}authentication/createpassword/basic`, title: 'Basic' },
//     { path: `${import.meta.env.BASE_URL}authentication/createpassword/cover`, title: 'Cover' },

//     { path: `${import.meta.env.BASE_URL}authentication/lockscreen/lockscreenbasic`, title: 'Lockscreenbasic' },
//     { path: `${import.meta.env.BASE_URL}authentication/lockscreen/lockscreencover`, title: 'Lockscreencover' },

//     { path: `${import.meta.env.BASE_URL}authentication/resetpassword/resetbasic`, title: 'Resetbasic' },
//     { path: `${import.meta.env.BASE_URL}authentication/resetpassword/resetcover`, title: 'Resetcover' },

//     { path: `${import.meta.env.BASE_URL}authentication/signup/signupbasic`, title: 'Signupbasic' },
//     { path: `${import.meta.env.BASE_URL}authentication/signup/signupcover`, title: 'Signupcover' },

//     { path: `${import.meta.env.BASE_URL}authentication/signin/signinbasic`, title: 'Signinbasic' },
//     { path: `${import.meta.env.BASE_URL}authentication/signin/signincover`, title: 'Signincover' },

//     { path: `${import.meta.env.BASE_URL}authentication/twostepverification/twostepbasic`, title: 'Twostepbasic' },
//     { path: `${import.meta.env.BASE_URL}authentication/twostepverification/twostepcover`, title: 'Twostepcover' },

//     { path: `${import.meta.env.BASE_URL}authentication/undermaintenance`, title: 'Undermaintenance' },

//     { path: `${import.meta.env.BASE_URL}error/401error`, title: 'Error401' },
//     { path: `${import.meta.env.BASE_URL}error/404error`, title: 'Error404' },
//     { path: `${import.meta.env.BASE_URL}error/500error`, title: 'Error500' },

//     { path: `${import.meta.env.BASE_URL}uielements/alerts`, title: 'Alerts' },
//     { path: `${import.meta.env.BASE_URL}uielements/badge`, title: 'Badge' },
//     { path: `${import.meta.env.BASE_URL}uielements/breadcrumb`, title: 'Breadcrumb' },
//     { path: `${import.meta.env.BASE_URL}uielements/buttons`, title: 'Buttons' },
//     { path: `${import.meta.env.BASE_URL}uielements/buttongroup`, title: 'Buttongroup' },
//     { path: `${import.meta.env.BASE_URL}uielements/cards`, title: 'Cards' },
//     { path: `${import.meta.env.BASE_URL}uielements/dropdowns`, title: 'Dropdowns' },
//     { path: `${import.meta.env.BASE_URL}uielements/imagesfigures`, title: 'Imagesfigures' },
//     { path: `${import.meta.env.BASE_URL}uielements/listgroup`, title: 'Listgroup' },
//     { path: `${import.meta.env.BASE_URL}uielements/navtabs`, title: 'Navtabs' },
//     { path: `${import.meta.env.BASE_URL}uielements/objectfit`, title: 'Objectfit' },
//     { path: `${import.meta.env.BASE_URL}uielements/pagination`, title: 'Pagination' },
//     { path: `${import.meta.env.BASE_URL}uielements/popoovers`, title: 'Popoovers' },
//     { path: `${import.meta.env.BASE_URL}uielements/progress`, title: 'Progress' },
//     { path: `${import.meta.env.BASE_URL}uielements/spinners`, title: 'Spinners' },
//     { path: `${import.meta.env.BASE_URL}uielements/toasts`, title: 'Toasts' },
//     { path: `${import.meta.env.BASE_URL}uielements/tooltips`, title: 'Tooltips' },
//     { path: `${import.meta.env.BASE_URL}uielements/typography`, title: 'Typography' },

//     { path: `${import.meta.env.BASE_URL}utilities/avatars`, title: 'Avatars' },
//     { path: `${import.meta.env.BASE_URL}utilities/borders`, title: 'Borders' },
//     { path: `${import.meta.env.BASE_URL}utilities/breakpoints`, title: 'Breakpoints' },
//     { path: `${import.meta.env.BASE_URL}utilities/colors`, title: 'Colors' },
//     { path: `${import.meta.env.BASE_URL}utilities/columns`, title: 'Columns' },
//     { path: `${import.meta.env.BASE_URL}utilities/flex`, title: 'Flex' },
//     { path: `${import.meta.env.BASE_URL}utilities/gutters`, title: 'Gutters' },
//     { path: `${import.meta.env.BASE_URL}utilities/helpers`, title: 'Helpers' },
//     { path: `${import.meta.env.BASE_URL}utilities/position`, title: 'Position' },
//     { path: `${import.meta.env.BASE_URL}utilities/additionalcontent`, title: 'Additionalcontent' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/inputs`, title: 'Inputs' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/checksradios`, title: 'Checksradios' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/inputgroup`, title: 'Inputgroup' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/formselect`, title: 'Formselect' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/rangeslider`, title: 'Rangeslider' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/inputmasks`, title: 'Inputmasks' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/fileuploads`, title: 'Fileuploads' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/datetimepicker`, title: 'Datetimepicker' },
//     { path: `${import.meta.env.BASE_URL}forms/formelements/colorpickers`, title: 'Colorpickers' },

//     { path: `${import.meta.env.BASE_URL}forms/floatinglabel`, title: 'Floatinglabel' },
//     { path: `${import.meta.env.BASE_URL}forms/formlayouts`, title: 'Formlayouts' },
//     { path: `${import.meta.env.BASE_URL}forms/validation`, title: 'Validation' },
//     { path: `${import.meta.env.BASE_URL}forms/select2`, title: 'Select2' },

//     { path: `${import.meta.env.BASE_URL}forms/formeditor/quilleditor`, title: 'Quilleditor' },

//     { path: `${import.meta.env.BASE_URL}advancedui/accordionscollapse`, title: 'Accordionscollapse' },
//     { path: `${import.meta.env.BASE_URL}advancedui/carousel`, title: 'Carousel' },
//     { path: `${import.meta.env.BASE_URL}advancedui/draggablecards`, title: 'Draggablecards' },
//     { path: `${import.meta.env.BASE_URL}advancedui/modalscloses`, title: 'Modalscloses' },
//     { path: `${import.meta.env.BASE_URL}advancedui/navbar`, title: 'Navbar' },
//     { path: `${import.meta.env.BASE_URL}advancedui/offcanvas`, title: 'Offcanvas' },
//     { path: `${import.meta.env.BASE_URL}advancedui/placeholders`, title: 'Placeholders' },
//     { path: `${import.meta.env.BASE_URL}advancedui/ratings`, title: 'Ratings' },
//     { path: `${import.meta.env.BASE_URL}advancedui/swiperjs`, title: 'Swiperjs' },

//     { path: `${import.meta.env.BASE_URL}widgets`, title: 'Widgets' },

//     { path: `${import.meta.env.BASE_URL}apps/fullcalendar`, title: 'Fullcalendar' },
//     { path: `${import.meta.env.BASE_URL}apps/gallery`, title: 'Gallery' },
//     { path: `${import.meta.env.BASE_URL}apps/sweetalerts`, title: 'Sweetalerts' },

//     { path: `${import.meta.env.BASE_URL}apps/projects/projectslist`, title: 'Projectslist' },
//     { path: `${import.meta.env.BASE_URL}apps/projects/projectoverview`, title: 'Projectoverview' },
//     { path: `${import.meta.env.BASE_URL}apps/projects/createproject`, title: 'Createproject' },

//     { path: `${import.meta.env.BASE_URL}apps/jobs/jobdetails`, title: 'Jobdetails' },
//     { path: `${import.meta.env.BASE_URL}apps/jobs/searchcompany`, title: 'Searchcompany' },
//     { path: `${import.meta.env.BASE_URL}apps/jobs/searchjobs`, title: 'Searchjobs' },
//     { path: `${import.meta.env.BASE_URL}apps/jobs/jobpost`, title: 'Jobpost' },
//     { path: `${import.meta.env.BASE_URL}apps/jobs/jobslist`, title: 'Jobslist' },
//     { path: `${import.meta.env.BASE_URL}apps/jobs/searchcandidate`, title: 'Searchcandidate' },
//     { path: `${import.meta.env.BASE_URL}apps/jobs/candidatedetails`, title: 'Candidatedetails' },

//     { path: `${import.meta.env.BASE_URL}apps/nft/marketplace`, title: 'Marketplace' },
//     { path: `${import.meta.env.BASE_URL}apps/nft/nftdetails`, title: 'Nftdetails' },
//     { path: `${import.meta.env.BASE_URL}apps/nft/createnft`, title: 'Createnft' },
//     { path: `${import.meta.env.BASE_URL}apps/nft/walletintegration`, title: 'Walletintegration' },
//     { path: `${import.meta.env.BASE_URL}apps/nft/liveauction`, title: 'Liveauction' },

//     { path: `${import.meta.env.BASE_URL}apps/crm/crmcontacts`, title: 'Crmcontacts' },
//     { path: `${import.meta.env.BASE_URL}apps/crm/companies`, title: 'Companies' },
//     { path: `${import.meta.env.BASE_URL}apps/crm/deals`, title: 'Deals' },
//     { path: `${import.meta.env.BASE_URL}apps/crm/leads`, title: 'Leads' },

//     { path: `${import.meta.env.BASE_URL}apps/crypto/transactions`, title: 'Transactions' },
//     { path: `${import.meta.env.BASE_URL}apps/crypto/currencyexchange`, title: 'Currencyexchange  ' },
//     { path: `${import.meta.env.BASE_URL}apps/crypto/buysell`, title: 'Buysell' },
//     { path: `${import.meta.env.BASE_URL}apps/crypto/marketcap`, title: 'Marketcap' },
//     { path: `${import.meta.env.BASE_URL}apps/crypto/wallet`, title: 'Wallet' },

//     { path: `${import.meta.env.BASE_URL}tables/tables`, title: 'Tables' },
//     { path: `${import.meta.env.BASE_URL}tables/gridjstables`, title: 'Gridjstables' },
//     { path: `${import.meta.env.BASE_URL}tables/datatables`, title: 'Datatables' },

//     { path: `${import.meta.env.BASE_URL}apexcharts/linecharts`, title: 'Linecharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/areacharts`, title: 'Areacharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/columncharts`, title: 'Columncharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/barcharts`, title: 'Barcharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/mixedcharts`, title: 'Mixedcharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/rangeareacharts`, title: 'Rangeareacharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/timelinecharts`, title: 'Timelinecharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/candlestickcharts`, title: 'Candlestickcharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/boxplotcharts`, title: 'Boxplotcharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/bubblecharts`, title: 'Bubblecharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/scattercharts`, title: 'Scattercharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/heatmapcharts`, title: 'Heatmapcharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/treemapcharts`, title: 'Treemapcharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/piecharts`, title: 'Piecharts ' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/radialbarcharts`, title: 'Radialbarcharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/polarareacharts`, title: 'Polarareacharts' },
//     { path: `${import.meta.env.BASE_URL}apexcharts/radarcharts`, title: 'Radarcharts' },

//     { path: `${import.meta.env.BASE_URL}charts/chartjscharts`, title: 'Chartjscharts' },
//     { path: `${import.meta.env.BASE_URL}charts/echartscharts`, title: 'Echartscharts' },

//     { path: `${import.meta.env.BASE_URL}maps/googlemaps`, title: 'Googlemaps' },
//     { path: `${import.meta.env.BASE_URL}maps/leafletmaps`, title: 'Leafletmaps' },
//     { path: `${import.meta.env.BASE_URL}maps/vectormaps`, title: 'Vectormaps' },

//     { path: `${import.meta.env.BASE_URL}icons`, title: 'Icons' },
// ];
